project:
  type: book
  output-dir: _book

lang: zh

book:
  title: "270-book-reference-reading"
  author: "wisGens"
  date: "2022/11/3"
  chapters:
    - index.qmd
    - intro.qmd
    - Metabolic and epigenetic regulation of T-cell exhaustion.qmd
    - summary.qmd
    - references.qmd

  search: true
  downloads: [pdf]

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true
    crossref:
      chapters: true
      eq-prefix: ""
  pdf:
    documentclass: ctexbook
    classoption: [UTF8,twoside,openany,table]
    keep-tex: false
    lof: true
    lot: true
    toc: true
    toc-depth: 3
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm
    highlight-style: github
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    link-citations: true
    crossref:
      chapters: true
      eq-prefix: ""

editor: visual

